### ISSUE TITLE
<Can> without subject

### ISSUE THREAD

**Issue by LyhjeHylje** [stalniy/casl#107]
I have a flat component permission-wise, I do not really use the "of" -part (or subject) of the <Can> component. 
Casl seems to work fine with me leaving it out but the React component gives prop type warnings. 
I have worked around this by creating a custom can-component but I'm wondering if the prop-type validation could be loosened or if there is a more elegant way handling cases like:
`<Can I="post" />`

**Tasks**:
- [x] update types for `ForbiddenError.throwUnlessCan`
- [x] update types for `can`, `cannot`, `relevantRuleFor`, rulesFor`, `possibleRulesFor` of `Ability`
- [x] update types for `can` & `cannot` of `AbilityBuilder`
- [x] `casl/angular`
- [x] `casl/aurelia`
- [x] `casl/vue`
- [x] `casl/react`
- [x] add tests for casl/ability

**Comment by stalniy** [comment]
I thought about this recently. Actually it's a valid use case when app has a simple permission system which is based only on actions.

My thoughts on this:
- [ ]  `Ability`'s and `AbilityBuilder`'s `can` & `cannot` functions should have subject by default equal to `Object` ("by default" means if omitted)
- [ ] make subject optional for Vue and React `<Can>` components

**Comment by shellydehaven** [comment]
CASL is awesome - thank you!  Looking forward to this being addressed.  Any thoughts on when it will be available?

**Comment by stalniy** [comment]
Currently I’m pretty busy at my job, so it’s hard to say. But PRs are welcome :)

Meanwhile you can define permissions using `all` subject and create a simple wrapper around ability which uses `all` subject as default value.

**Comment by stalniy** [comment]
After some thinking about this, I realised that on `@casl/ability` level it can be implemented without changes. The only thing which you need to do is to define custom `subjectName` function:

```js
const subjectName = () => 'all'

const ability = AbilityBuilder.define({ subjectName }, (can) => {
  can('read')
  can('think')
})

console.log(ability.can('think')) // true
console.log(ability.can('write')) // false
```

The only thing which needs to be changed is Typescript declarations and complementary packages

**Comment by stalniy** [comment]
will be available in casl 4.x
