### ISSUE TITLE
Rewrite packages to Typescript

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#248]
The good point is that I won't need to support `d.ts` files manually (what I sometimes forget to do).

## Challenges

- investigate eslint for typescript
- investigate rollup for typescript

## Todo

- [x] simplify rollup setup for different output targets
- [x] typescript + babel
- [x] typescript + eslint?
- [x] ability
- [x] enable eslint for angular
- [x] vue
- [x] react
- [x] aurealia
- [x] mongoose
- [x] test types in example apps
