### ISSUE TITLE
Decrease lib size

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#249]
**Tasks**:
- [x] create a separate `Ability` class for Mongo like conditions
- [x] use only few mostly used operators from sift
- [x] use https://github.com/terser/terser instead of uglify. mangle private properties instead of hiding them under `Symbol` 
- [x] update tests to use `defineAbility` instead of `AbilityBuilder.define`

**Comment by stalniy** [comment]
blocked by https://github.com/crcn/sift.js/issues/181

**Comment by stalniy** [comment]
issues in sift has been fixed
